version: '2'
services:
  django:
    container_name: libmain_api
    build: ./django
    volumes:
            - ./django:/code:rw
    ports:
      - "8080:8080"
    links:
      - mongo
      - rabbitmq
      - memcached
  nginx:
    container_name: libmain_nginx
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - django
  celery:
    container_name: libmain_celery
    build: ./celery
    links:
      - mongo
      - rabbitmq
  mongo:
    container_name: libmain_mongo
    image: mongo
  rabbitmq:
    container_name: libmain_rabbitmq
    image: rabbitmq
  memcached:
    container_name: libmain_memcache
    image: memcached
